spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sorveteria
    username: icecream_user
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  docker:
    compose:
      enabled: false

  rabbitmq:
    # URI completa do CloudAMQP (verifique se suas credenciais estão corretas)
    addresses: jackal.rmq.cloudamqp.com:5671
    username: kmskovrf
    password: Ei9fF3bR2B6P_7_R_vaxARNfCXkKqj1d
    virtual-host: kmskovrf
    ssl:
      enabled: true
    # Configurações de conexão
    connection-timeout: 30000
    requested-heartbeat: 30
    # Retry em caso de falha
    template:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 3
        multiplier: 2
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2
        acknowledge-mode: auto
        prefetch: 1