spring:
  rabbitmq:
    addresses: amqps://kmskovrf:9ulQT4f0BTIwr3xbnT4D6jJ95Dk3VRho@jackal.rmq.cloudamqp.com/kmskovrf
    username: kmskovrf
    password: 9ulQT4f0BTIwr3xbnT4D6jJ95Dk3VRho
    virtual-host: kmskovrf
  datasource:
    url: jdbc:postgresql://localhost:5432/sorveteria
    username: icecream_user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
     enabled: true
     locations: classpath:db/migration
